apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-db-url
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  # as we use a lower case key name transformer in our ClusterSecretStore
  # we need to access our 'CREDS' key in Doppler as 'creds'
  dataFrom:
    - find:
        path: creds

  # Create a Kubernetes Secret just as we're used to without External Secrets Operator
  target:
    name: aws-secrets-from-doppler