apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: aws-secrets-from-doppler

  # as we use a lower case key name transformer in our ClusterSecretStore
  # we need to access our 'CREDS' key in Doppler as 'creds'
  dataFrom:
    - find:
        path: creds