apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-auth-api
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: default
      # using a key name transformer https://external-secrets.io/latest/provider/doppler/#5-name-transformer
      # to get the lower case key name (as in the Crossplane docs)
      nameTransformer: lower-snake